name: mantan_pos
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  google_fonts: ^4.0.4
  firebase_auth: ^4.6.3
  firebase_ui_database: ^1.3.3
  firebase_storage: ^11.1.1

  # UI
  flutter_easyloading: ^3.0.5
  shimmer: ^2.0.0
  dropdown_textfield: ^1.0.8
  shared_preferences: ^2.1.2
  image_picker: ^0.8.9
  currency_text_input_formatter: ^2.1.10

  # Chart
  d_chart: ^2.2.11

  # QR
  qr_flutter: ^4.1.0
  responsive_ui: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Rename APP Name
  flutter_app_name: ^0.1.1

flutter_app_name:
  name: "Mantan POS"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
